name: flutter_reactive_ble_example
description: Demonstrates how to use the flutter_reactive_ble plugin.
version: 5.3.1
publish_to: 'none'

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: ">=2.0.0"

dependencies:
  permission_handler: 11.3.1
  uuid: 4.4.0
  flutter:
    sdk: flutter
  flutter_joybuttons: ^1.0.3
  flutter_reactive_ble: ^5.3.1
  functional_data: ^1.0.0
  intl: ^0.19.0

  provider: ^6.0.1

dev_dependencies:
  build_runner: ^2.3.3
  dependency_validator: ^3.1.0
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  functional_data_generator: ^2.1.0

dependency_overrides:
  flutter_reactive_ble:
    path: C:\Users\Lenovo\Desktop\flutter_philipshue\flutter_reactive_ble\packages\flutter_reactive_ble
  reactive_ble_mobile:
    path: C:\Users\Lenovo\Desktop\flutter_philipshue\flutter_reactive_ble\packages\reactive_ble_mobile
  reactive_ble_platform_interface:
    path: C:\Users\Lenovo\Desktop\flutter_philipshue\flutter_reactive_ble\packages\reactive_ble_platform_interface

flutter:
  uses-material-design: true
